server:
  applicationConnectors:
    - type: http
      port: 8888
  adminConnectors:
    - type: http
      port: 8889

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:../target/example;AUTO_SERVER=TRUE

logging:
  level: INFO
  loggers:
    org.hibernate.SQL:
      level: DEBUG
